'use strict';
angular.module('LeadService',[]).factory('LeadService', function() {

	var leads = [
	  {	
	  	id: "1",
	  	owner: "Sara Bach",
	  	name: "John Smith",
	  	title: "Designer",
	  	company: "Capriza",
	  	engage: "3/23/2015",
	  	phone: "650-112-3456",
	  	email: "john@capriza.com",
	  	status: "Qualified",
	  	rating: "Hot",
	  	addr: "400 Hamilton Ave, Palo Alto, CA",
	  	website: "capriza.com",
	  	revenue: "$8,000,000",
	  	n_employee: "1204",
	  	desc: "Capriza is a great opportunity for us",
	  	industry: "",
	  	lead_src: "Trade Show",
	  	created_by: "Sara Bach, 8/08/15 2:35 PM",
	  	last_edited: "Sara Bach, 8/09/15, 3:30 PM",
	  	tag: "recent"
	  }, 
	  {	
	  	id: "2",
	  	owner: "Sharleen Tu",
	  	name: "Jesse Williams",
	  	title: "Sales",
	  	company: "Wells Fargo",
	  	engage: "6/6/2015",
	  	phone: "120-332-3333",
	  	email: "jesse@gmail.com",
	  	status: "open",
	  	rating: "",
	  	addr: "10 Jordan Ave, Cupertino, CA",
	  	website: "wellsfargo.com",
	  	revenue: "$300,000",
	  	n_employee: "12,534",
	  	desc: "Definitely follow up on this lead",
	  	industry: "Financial Services",
	  	lead_src: "Email Campaign",
	  	created_by: "Sharleen Tu, 5/08/15 2:33 PM",
	  	last_edited: "Sharleen Tu, 5/09/15, 3:50 PM",
	  	tag: "unread"
	  }, 
	  {	
	  	id: "3",
	  	owner: "Aaron Levie",
	  	name: " Jonathon Hen",
	  	title: "SVP Engineering",
	  	company: "Universal Studios",
	  	engage: "1/2/2014",
	  	phone: "909-919-9247",
	  	email: "jonathon@universal.com",
	  	status: "Open",
	  	rating: "Warm",
	  	addr: "12 Universal Dr, Hollywood, CA",
	  	website: "universalstudios.com",
	  	revenue: "$82,000,000",
	  	n_employee: "45,564",
	  	desc: "n/a",
	  	industry: "Entertainment",
	  	lead_src: "Advertisement",
	  	created_by: "Aaron Levie, 4/08/15 11:00 AM",
	  	last_edited: "Aaron Levie, 4/19/15, 11:50 AM",
	  	tag: "recent"
	  }, 
	  {	
	  	id: "4",
	  	owner: "Iris Choo",
	  	name: "Aaron Sing",
	  	title: "Consultant",
	  	company: "Coca Cola",
	  	engage: "8/2/2015",
	  	phone: "150-292-3056",
	  	email: "aaron@cocacola.com",
	  	status: "Open",
	  	rating: "Warm",
	  	addr: "2400 Garage Drive, Fremont, CA",
	  	website: "cocacola.com",
	  	revenue: "$12,000,000",
	  	n_employee: "391,928",
	  	desc: "Interesting use cases - follow up in two weeks",
	  	industry: "Beverages",
	  	lead_src: "Public Relations",
	  	created_by: "Iris Choo, 8/01/15 2:22 PM",
	  	last_edited: "Iris Choo, 8/01/15, 6:10 PM",
	  	tag: "unread"
	  }, 
	  {	
	  	id: "5",
	  	owner: "Amanda Reese",
	  	name: "Kevin Smith",
	  	title: "Engineer",
	  	company: "Stanford",
	  	engage: "1/1/2015",
	  	phone: "650-112-3456",
	  	email: "kevin@stanford.edu",
	  	status: "Qualified",
	  	rating: "Hot",
	  	addr: "10 Stanford Ave, Palo Alto, CA",
	  	website: "stanford.edu",
	  	revenue: "$200,000",
	  	n_employee: "23,434",
	  	desc: "n/a",
	  	industry: "Academia",
	  	lead_src: "External Referral",
	  	created_by: "Amanda Reese, 8/11/15 12:33 PM",
	  	last_edited: "Amanda Reese, 8/12/15, 9:10 PM",
	  	tag: "recent"
	  }, 
	  {	
	  	id: "6",
	  	owner: "Jake Magg",
	  	name: "Angad Singh",
	  	title: "Sales Engineer",
	  	company: "TF Construction",
	  	engage: "",
	  	phone: "900-194-1156",
	  	email: "jakemagg@capriza.com",
	  	status: "open",
	  	rating: "hot",
	  	addr: "19245 Corolla Ave, Cupertino, CA",
	  	website: "tfconstruction.com",
	  	revenue: "$120,000",
	  	n_employee: "344",
	  	desc: "n/a",
	  	industry: "Construction",
	  	lead_src: "Word of Mouth",
	  	created_by: "Jake Magg, 8/08/15 2:33 PM",
	  	last_edited: "Jake Magg, 8/09/15, 3:50 PM",
	  	tag: "recent"
	  }, 
	  {	
	  	id: "7",
	  	owner: "Sharleen Tu",
	  	name: "Alison Wonderland",
	  	title: "CFO",
	  	company: "Records Inc.",
	  	engage: "",
	  	phone: "209-114-1246",
	  	email: "alison@wonderland.com",
	  	status: "open",
	  	rating: "warm",
	  	addr: "19245 Corolla Ave, Cupertino, CA",
	  	website: "capriza.com",
	  	revenue: "$120,000",
	  	n_employee: "344",
	  	desc: "n/a",
	  	industry: "Construction",
	  	lead_src: "Word of Mouth",
	  	created_by: "Sharleen Tu, 8/012/15 6:33 PM",
	  	last_edited: "Sharleen Tu, 8/14/15, 3:50 PM",
	  	tag: "today"
	  }, 
	  {	
	  	id: "8",
	  	owner: "Josh Williams",
	  	name: "Pat Cruz",
	  	title: "VP of Innovation",
	  	company: "Petco",
	  	engage: "",
	  	phone: "510-111-9956",
	  	email: "cruz.pat@petco.com",
	  	status: "open",
	  	rating: "warm",
	  	addr: "145 Fremont Ave, Seattle, WA",
	  	website: "petco.com",
	  	revenue: "$1,120,090",
	  	n_employee: "32,944",
	  	desc: "n/a",
	  	industry: "",
	  	lead_src: "Tradeshow",
	  	created_by: "Josh Williams, 8/04/15 11:33 PM",
	  	last_edited: "Josh Williams, 8/09/15, 3:50 PM",
	  	tag: "today"
	  }
	];


  return {
    all: function() {
      return leads;
    },
    add: function(new_lead) {
      return leads.push(new_lead);
    }
  };

});

